<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Product;
use AppBundle\Entity\User;

/**
 * AffiliateRequestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffiliateRequestsRepository extends \Doctrine\ORM\EntityRepository
{


    public function isAlreadyRequested(User $user, Product $product) {
        $request = $this->findBy(array('user' => $user, 'product' => $product));

        if (count($request) == 0) {
            return false;
        } else {
            return true;
        }
    }

}
