<?php

namespace AppBundle\Repository;

/**
 * APIsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class APIsRepository extends \Doctrine\ORM\EntityRepository
{
}
