<?php

namespace AppBundle\Repository;

/**
 * AutoresponderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutoresponderRepository extends \Doctrine\ORM\EntityRepository
{
}
