<?php

namespace AppBundle\Repository;

/**
 * PhoneConfirmationCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneConfirmationCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
