<?php

namespace AppBundle\Repository;

/**
 * SalesFunnelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesFunnelRepository extends \Doctrine\ORM\EntityRepository
{
}
