<?php

namespace AppBundle\Repository;

/**
 * SalesFunnelProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesFunnelProductRepository extends \Doctrine\ORM\EntityRepository
{
}
