<?php

namespace AppBundle\Repository;

/**
 * SiteStatisticsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteStatisticsRepository extends \Doctrine\ORM\EntityRepository
{
}
