<?php

namespace AppBundle\Repository;

/**
 * SupportPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupportPostRepository extends \Doctrine\ORM\EntityRepository
{
}
