<?php

namespace AppBundle\Repository;

/**
 * SupportPostReplyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupportPostReplyRepository extends \Doctrine\ORM\EntityRepository
{
}
