<?php

namespace AppBundle\Repository;

/**
 * TrustedAffiliateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrustedAffiliateRepository extends \Doctrine\ORM\EntityRepository
{
}
